FROM openjdk:11-slim-buster
MAINTAINER Yimik <398075986@163.com>

RUN apt update && apt install -y ttf-dejavu && apt install -y tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
ADD fonts/* /usr/share/fonts/truetype/
