FROM eclipse-temurin:17-jdk-jammy
LABEL author="Yimik <398075986@163.com>"

ADD fonts/* /usr/share/fonts/truetype/

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update &&  \
    apt install -y fonts-noto-cjk fonts-wqy-microhei fonts-wqy-zenhei xfonts-wqy ttf-mscorefonts-installer ttf-dejavu tzdata libfreetype6 fontconfig &&  \
    fc-cache && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&  \
    echo 'Asia/Shanghai' >/etc/timezone
